# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit_linear <- function(X, Y, mu, sigma, gamma, alpha, beta, lambda, update_order, prior, max_iter, tol) {
    .Call(`_sparsevb_fit_linear`, X, Y, mu, sigma, gamma, alpha, beta, lambda, update_order, prior, max_iter, tol)
}

fit_logistic <- function(X, Y, mu, sigma, gamma, alpha, beta, lambda, update_order, prior, max_iter, tol) {
    .Call(`_sparsevb_fit_logistic`, X, Y, mu, sigma, gamma, alpha, beta, lambda, update_order, prior, max_iter, tol)
}

